import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers";
import NavBar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Providers>
        <body
          className={`${geistSans.variable} ${geistMono.variable} font-mono antialiased`}
        >
          <div className='font-mono h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 flex flex-col'>
            <div>
              <NavBar />
            </div>

            {children}
          </div>
        </body>
      </Providers>
    </html>
  );
}
