import NavBar from "@/components/Navbar";
import Providers from "@/components/providers";
import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Providers>
        <body className={`${jetBrainsMono.className} font-mono antialiased`}>
          <div className='flex flex-col h-screen font-mono bg-gradient-to-br from-slate-900 via-blue-900 to-slate-900'>
            <div>
              <NavBar />
            </div>
            <Suspense>{children}</Suspense>
          </div>
        </body>
      </Providers>
    </html>
  );
}
